# Generated by Django 4.2 on 2023-11-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='إسم الدورة')),
                ('short_name', models.CharField(max_length=100, verbose_name='إختصار الإسم')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('price', models.CharField(max_length=100, verbose_name='سعر')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='إسم الحدث')),
                ('image', models.CharField(max_length=100, verbose_name='الصورة')),
                ('date', models.CharField(max_length=100, verbose_name='تاريخ الحدث')),
                ('type', models.CharField(max_length=100, verbose_name='نوع الحدث')),
            ],
            options={
                'verbose_name': 'حدث',
                'verbose_name_plural': 'الأحداث',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('link', models.URLField(verbose_name='الرابط')),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='news/', verbose_name='الصورة')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='إسم التخصص')),
                ('short_name', models.CharField(max_length=100, verbose_name='إختصار الإسم')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='team/', verbose_name='الصورة')),
                ('mail', models.EmailField(max_length=100, verbose_name='البريد الالكتروني')),
                ('facebook', models.URLField(max_length=100, verbose_name='الفيس بوك')),
                ('youtube', models.URLField(max_length=100, verbose_name='اليوتيوب')),
            ],
            options={
                'verbose_name': 'فريق',
                'verbose_name_plural': 'الفريق',
                'ordering': ['-id'],
            },
        ),
    ]
