# Generated by Django 4.2 on 2023-11-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(verbose_name='لينك صورة الخبر'),
        ),
    ]
