# Generated by Django 4.2 on 2023-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('link', models.URLField(verbose_name='لينك الفيديو')),
                ('background_img_link', models.URLField(verbose_name='لينك صورة الفيديو')),
                ('created_at', models.DateField(auto_now=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'المدونة',
                'verbose_name_plural': 'المدونات',
            },
        ),
    ]
