# Generated by Django 4.2 on 2023-11-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=100, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='تفاصيل الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='اللينك'),
        ),
    ]
