# Generated by Django 4.2 on 2023-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_description_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='لينك صورة الخبر'),
        ),
    ]
